### ISSUE TITLE
[Suggestion] New Logo Design For ZimLX

### ISSUE THREAD

**Issue by zularizal** [otakuhqz/ZimLX#1]
Hi, I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good, but on this logo looks less interesting. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by otakuhqz** [comment]
Hello Zularizal, Thank you su much for your interest on this.
As I'm working alone in this project I had not chance to take care in the icons and logo.
If you can design something for the app, I will be grateful with you.

Thank you

**Comment by zularizal** [comment]
Hi, I've made 3 pieces of sample logo, what do you think? which one do you like? If you want something to change tell me

![logo](https://user-images.githubusercontent.com/38547278/40949011-0bc1b2a6-6896-11e8-960f-f6a793ea4377.png)

**Comment by otakuhqz** [comment]
I like the third option. but I would like to make two changes:
1 - Can you please change the shape to be squared with rounded corners? similar to the ios icons
2 - I like the gradient color, but I do prefer a green instead of purple.
what do you think?

**Comment by zularizal** [comment]
Hi @otakuhqz , Do you mean like this? 

![g4104](https://user-images.githubusercontent.com/38547278/41056857-aad74bbc-69ef-11e8-81f8-5d256bd281e3.png)

**Comment by otakuhqz** [comment]
I like it. Which one like most to to you?

**Comment by zularizal** [comment]
I think it looks nice and elegant. If you like this, I will send a pull request for you

**Comment by otakuhqz** [comment]
Thank you so much.Please send the pull request.

**Comment by zularizal** [comment]
Hi @otakuhqz , i have sent a pull request for you
check #2

**Comment by otakuhqz** [comment]
I have tested in the application and I would like to make a small changes in the icon.
I will share some screen shots later so you can see how it looks like and have your opinion before make any changes.

**Comment by zularizal** [comment]
Okay, you can send it here.

**Comment by zularizal** [comment]
Check new pull request, i have make it look rounded

**Comment by otakuhqz** [comment]
Hi @zularizal,
I was thinking to have the square shape but having the corners with a deeper radius.
like the below image.
However after checking what you submit I think it is ok rounded as you did.
<img src="https://user-images.githubusercontent.com/38547278/41056857-aad74bbc-69ef-11e8-81f8-5d256bd281e3.png" width="64">

I will close this issue. Thank you su much for your help
![screenshot_1530824977](https://user-images.githubusercontent.com/6044050/42348398-89ac8b4a-8066-11e8-8b39-a8f02657f79c.png)

**Comment by zularizal** [comment]
Okay, i will close this issue
