### ISSUE TITLE
Weather

### ISSUE THREAD

**Issue by ildar** [otakuhqz/ZimLX#10]
Please bring it back. Basing on OWM basically but would be nice to have a choice

**Comment by otakuhqz** [comment]
I decide to remove it becase of the licence incompatability. I'm looking for an alternative to bring it back.

**Comment by otakuhqz** [comment]
I have this feature implemented in the new version taking Google as Source.
This feature is included in the new version v0.6.1 build 3009 which will be released within the next couple of days.
