### ISSUE TITLE
Drawer button

### ISSUE THREAD

**Issue by baltitenger** [otakuhqz/ZimLX#12]
### Issue:
The drawer button is forced to be in the dock, but if you temporarily reduce the number of items in the dock, you can get an icon on top of it:
![drawer](https://user-images.githubusercontent.com/21960678/52375187-581bfe00-2a5f-11e9-8383-a0586c5c7231.png)

### Proposed solution:
The drawer button should be optional.

### Smartphone:
 - Device: Xiaomi Mi A1
 - OS: ResurrectionRemix v7.0.0 (Android 9)

**Comment by hummer010** [comment]
I was just coming to report this issue.

I'd also like the drawer button to be optional.

**Comment by otakuhqz** [comment]
I made a lot of changes in v0.50, and i'm still migrating some features. I will add this feature in dock settings.

**Comment by otakuhqz** [comment]
Fixed on v0.5.2
