### ISSUE TITLE
Search without google

### ISSUE THREAD

**Issue by baltitenger** [otakuhqz/ZimLX#15]
If the Google app is not installed, the searchbar or "Google Search pill" will not be visible. You should add a Google-independent alternative, where you could specify the query URL, like `https://duckduckgo.com?q=%s` or something similar.

**Comment by otakuhqz** [comment]
I have added this feature on v0.5.2. At this time only work. I will include more features in the next versions.

**Comment by ohnonot** [comment]
@otakuhqz  I am sorry, I did not quite understand your answer-  
Do you mean that currently only the original google search bar is supported?

I would also like to see an alternative, but I'm not sure how this would have to be implemented.  
3rd party app? I couldn't find an alternative on f-droid. or from within the launcher?
