### ISSUE TITLE
Typo in Settings -> Others -> Advanced 

### ISSUE THREAD

**Issue by add1son** [otakuhqz/ZimLX#17]
**Describe the bug**
It appears that in Settings -> Others -> Advanced "Languaje and backup" is present when I am guessing it is intended to read "language". 

**To Reproduce**
1. Go to Settings
2. Scroll down to Others

**Screenshots**
![image](https://user-images.githubusercontent.com/25604843/52587476-fe189100-2dee-11e9-80da-13c37207eefe.png)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: 9

**Comment by otakuhqz** [comment]
Fixed on v0.5. I will post the compiled apk soon.
Thanks
