### ISSUE TITLE
Two versions of ZimLX - based of code from OpenLauncher and Lawnchair

### ISSUE THREAD

**Issue by DI555** [otakuhqz/ZimLX#18]
I'd like to suggest to build two versions of ZimLX  - based of code from OpenLauncher and Lawnchair!
OpenLauncher and Lawnchair are so different and they have many different little features, so would be great to use one of both, or even both launchers!!!
I honestly like more OpenLauncher base, and it's not droped now - today work in progress.
(And Lawnchair v1 imho freezed in developing, v2 is unstable, buggy and may not work fine)
Another benefit - one of OpenLauncher/Lawnchair may not work on some devices, but two versions of ZimLX may solve that thing!

**Comment by otakuhqz** [comment]
That would be great but it's hard to do it since they are complete different. What I try to do is to have the best features of both of them in the same launcher and make it customizable as much as possible.
if you suggest a specific feature I will be glad to work on it.

**Comment by DI555** [comment]
Ok, thank you! I'll try to suggest many interest things)!

**Comment by otakuhqz** [comment]
Thanks @DI555, I'll be looking forward to your suggestions.

**Comment by DI555** [comment]
@otakuhqz , but why did you get decision to skip to lawnchair code base?
It's  imo more buggy...
I'm trying to ask..., do you have any thoughts to skip back to openlauncher code base;)?
