### ISSUE TITLE
Minibar cannot be switched off

### ISSUE THREAD

**Issue by ralxxx** [otakuhqz/ZimLX#22]
**Describe the bug**
The Minibar is an optional feature, that is supposed to be switched on/off under Settings > Desktop > Minibar. No matter if I swich it On or Off, the Minibar is there all the time.

**To Reproduce**
1. Go to 'Settings > Desktop > Minibar'
2. Click on 'Off'

**Expected behavior**
When it is switched off I suppose that the Minibar should be entirely blocked to appear.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device:Xiaomi Redmi 4x
 - OS: MIUI 10.1/Android 7.1

**Comment by otakuhqz** [comment]
it is working properly in v0.5.1.
are you using the v0.4.4 or minor?

**Comment by ralxxx** [comment]
I am on 0.4.4. the latest version currently available on F-Droid. 
If it is resolved then it's perfect. Thanks for quick feedback.

**Comment by otakuhqz** [comment]
Fixed on v0.5.1
