### ISSUE TITLE
F-droid not getting updated

### ISSUE THREAD

**Issue by baltitenger** [otakuhqz/ZimLX#24]
Currently F-droid only shows version 0.4.4

**Comment by otakuhqz** [comment]
the f-droid releases are not handled by me but F-Droid tream. I noted they are working on the new releases so I think they will be ready shortly.

**Comment by relan** [comment]
We can't update ZimLX on F-Droid because [0.4.4](https://github.com/otakuhqz/ZimLX/blob/v0.4.4/version.properties#L3) has a higher version code than [0.5.2](https://github.com/otakuhqz/ZimLX/blob/v0.5.2/version.properties#L3). See https://developer.android.com/studio/publish/versioning#appversioning.

**Comment by relan** [comment]
Version code issue is solved, but now we can't build 0.6.1 because release builds were disabled in 180d50cab92e285453740da0b92cf3dc5a74edfd.

**Comment by lameventanas** [comment]
> Version code issue is solved, but now we can't build 0.6.1 because release builds were disabled in [180d50c](https://github.com/otakuhqz/ZimLX/commit/180d50cab92e285453740da0b92cf3dc5a74edfd).

How about creating a pull request to fix this?

**Comment by otakuhqz** [comment]
I will enable it and will release as a new version

**Comment by otakuhqz** [comment]
fixed @lameventanas @relan

**Comment by relan** [comment]
@otakuhqz, should F-Droid build _aosp_ or _quickstep_ flavor?

**Comment by otakuhqz** [comment]
aosp.

**Comment by relan** [comment]
Added in https://gitlab.com/fdroid/fdroiddata/commit/cc665cc310f8914b4ab219a5a6c92a0fdfb54b60. Thanks!

**Comment by userkilled** [comment]
I can not install the launcher from F-Droid.  Error: The package is damaged. 0.6.2b

**Comment by relan** [comment]
@userkilled, what's your device and Android version?

**Comment by userkilled** [comment]
7.0

**Comment by baltitenger** [comment]
On Pie I get Error -15: the new package failed because it has specified that it is a test-only package and the caller has not supplied the INSTALL_ALLOW_TEST flag.

**Comment by otakuhqz** [comment]
@relan I had this problem with my own compiled version and just fixed yesterday by adding the below line to the graddle properties file.
Is it necessary to make a new release to fix the f-droid version?

`android.injected.testOnly=false`

**Comment by relan** [comment]
Wait. What's this https://github.com/otakuhqz/ZimLX/blob/master/ZimLX/libs/framework.jar? Is it possible to get rid of it? Prebuilt JARs are prohibited by the inclusion policy: https://f-droid.org/en/docs/Inclusion_Policy/

**Comment by otakuhqz** [comment]
Remove in commit [db477e5](https://github.com/otakuhqz/ZimLX/commit/db477e57eeed9b9195a41d8de13b7f06cbb95667).

What about this https://github.com/otakuhqz/ZimLX/blob/master/quickstep/libs/sysui_shared.jar?
should be removed too?

**Comment by relan** [comment]
> What about this https://github.com/otakuhqz/ZimLX/blob/master/quickstep/libs/sysui_shared.jar?
should be removed too?

It's in another flavor, but if you don't need it, better remove: when we enable automated checks for prebuilt binaries it will trigger an error.
