### ISSUE TITLE
[Feature Request] Widget overlap and Desktop lock

### ISSUE THREAD

**Issue by Graveen** [otakuhqz/ZimLX#25]
Hi,
Kudos for one of the best launcher available. Not only opensource, but also fast and customizable.

2 requests that would rock:
- widget overlap, so allows widget to be selected in the way they are added (latest added = active), with apps being over widget all the time
- desktop lock, to avoid icons / widget move

Thank you very much, excellent work !

**Comment by otakuhqz** [comment]
Thank you for your comments.
Regarding to the features required, I dot not understand the first one (sorry I'm not fully english speaker yet).

The second one, will be developed and included in the next releases.

**Comment by Graveen** [comment]
Thank you for your hard work. 
Widget overlap allows 2 widgets to be both at the same position. 
Useful for widget with plenty of space around like cLock :)

**Comment by otakuhqz** [comment]
this feature is implemented in the new version v0.6.1.
I will post a new release soon.
