### ISSUE TITLE
[Bug report] Dock height in 0.5.2

### ISSUE THREAD

**Issue by Graveen** [otakuhqz/ZimLX#26]
Dock in 0.5.2 is really small and the bottom of icons in dock is truncated,
Even when i increase dock size (to 150%) it seems not to work). 
In 0.4.4 dock was nice for me.

**Comment by Graveen** [comment]
![Screenshot_Zim_Launcher_20190315-092423](https://user-images.githubusercontent.com/537733/54420235-be083f00-4709-11e9-8e7f-b5d708cc3a30.png)

**Comment by otakuhqz** [comment]
the dock size preference is not working yet but will be fixed in the next version v0.5.3
I will make sure the height is fixed as well.

**Comment by otakuhqz** [comment]
Fixed in commit [Update Icon height scale](https://github.com/otakuhqz/ZimLX/commit/b3cbe706214596f1b3f31ae4e6f03af33cb66d9c)
