### ISSUE TITLE
Not visible apps drawer (installed apps) field.

### ISSUE THREAD

**Issue by DI555** [otakuhqz/ZimLX#27]
**Describe the bug**
Not visible apps drawer (installed apps) field.
Touchable but not visible.

**To Reproduce**
1. Swap from down to up in main screen.
2. Touch button 'installed apps' in bottom of screen.
3 . When the widget 'installed apps' is appeared it's visible, but when it reach 100% it's dissappeared(.
4. I have this bug on the first betas of lawnchair(. (nowaday's betas of lawnchair just have chrushing...)

**Expected behavior**
Visible view of 'installed apps'.

**Smartphone (please complete the following information):**
 - Device: [smartphone on spreadtrum sc7731 chip]
 - OS: [android 5.1]
 - Version [0.5.2 build 1065]

**Comment by otakuhqz** [comment]
Since I migrated to a newer version of Android AOSP and Lawnchair, this is already fixed.
