### ISSUE TITLE
Dock and drawer height issue 

### ISSUE THREAD

**Issue by Nathoufresh** [otakuhqz/ZimLX#29]
Scrrenshots here 
https://ibb.co/Wk9Ytd5
https://ibb.co/y4rTM9H

Crap, we can't really see it on the screenshots but in fact there's a little gap between the app and the bottom of the screen.  I'm using a Pocophone F1

**Comment by otakuhqz** [comment]
can you please confirm which version of ZimLX are you using?

**Comment by Nathoufresh** [comment]
0.4.4

**Comment by otakuhqz** [comment]
the issue has been resolved in the new versions, but f-droid is still working to compile the new version. If you want to try the new version, you can go to the release section.
