### ISSUE TITLE
App Drawer Folder

### ISSUE THREAD

**Issue by dmnkhmr** [otakuhqz/ZimLX#33]
Hey ncie work!

It would be great if you could create folders in the app drawer (like in Nova Launcher), to group apps of a certain category in one folder.

I have thousands of instant messaging apps which should be in one place.

br
Dominik

**Comment by otakuhqz** [comment]
I should have to re-write a lot of code but I think it could be implemented in the next releases.

**Comment by dmnkhmr** [comment]
That would be awesome and much appreciated!

**Comment by otakuhqz** [comment]
implemented in this [commit](https://github.com/otakuhqz/ZimLX/commit/3102e9c7d404c320d08ff292998fa2b922a6f3fc). will be available in the next release.
