### ISSUE TITLE
remove the drawer icon on desktop

### ISSUE THREAD

**Issue by oxxz** [otakuhqz/ZimLX#35]
**Is your feature request related to a problem? Please describe.**
i didnt know if i would post this as a bug or as a feature request. but i would like to be able to remove the app drawer icon on the desktop, but i cant remove it like any other app thats on the desktop (like i can do in lawnchair), and i cant find any option for it in the settings.

**Describe the solution you'd like**
be able to hold the icon and move it to the top to remove it, like any other app (and like its in lawnchair)

**Comment by otakuhqz** [comment]
Duplicated #12.
Already fixed on v0.5.2
