### ISSUE TITLE
[Feature Request] Please add back scaling icons below 75%

### ISSUE THREAD

**Issue by TobiasDev** [otakuhqz/ZimLX#37]
In an older versions of the launcher I could change the scale of the icons to 30% and I always had mine at 40% (I feel like it looks cleaner) would it be possible to add this option back? In the latest version I can only scale them to 75% which I still feel is too big. 

This is just a minor customization thing, but if possible I would love to see this come back.

**Comment by otakuhqz** [comment]
I think 40% is too small, however I will bring back the same scale as the previous versions.
a new version v0.6.1 build 3009 will be released within next days. I will include this change in this version.
