### ISSUE TITLE
The application is not being installed

### ISSUE THREAD

**Issue by XAMIR555** [otakuhqz/ZimLX#38]
#### Project Information
* Repository---------------:[Here](https://github.com/Ye-Miao/StatusBarUtil)
* Project Name------------: [StatusBarUtil](https://github.com/Ye-Miao/StatusBarUtil/releases)
* Publisher----------------: [ Leaf Ye-Miao](https://github.com/Ye-Miao)
* My GitHub account-----:  [Here](https://github.com/XAMIR555)

#### Expected behavior
The application should be installed when I try to install the application

#### Actual behavior

The application is not being installed

#### How to reproduce
* [Download ](https://github.com/Ye-Miao/StatusBarUtil)the application
* try to install the application
* Note the Bug

* Browser/App version-: v0.6.1
* Operating system----: 9.0.0

#### Recording Of The Bug

![20190528_014834](https://user-images.githubusercontent.com/49812927/58438936-6893cb00-8086-11e9-9a4f-5e2fa4ebcaf5.gif)

**Comment by shawn1thompson** [comment]
Same here on Moto g6 trying to update over current F Droid version (0.4.4)

**Comment by TobiasDev** [comment]
I have the same issue with the apk downloaded here from Github. OnePlus 3.

**Comment by TobiasDev** [comment]
I have the same problem with the latest apk as well. The one from yesterday.

**Comment by otakuhqz** [comment]
do you have the previous version installed? If so try uninstalling the old version.

**Comment by tjgordon** [comment]
@otakuhqz I uninstalled the previous version and still can't install it.

**Comment by TobiasDev** [comment]
Same for me, I currently don't have the app installed, but still can't install the new one.

**Comment by Graveen** [comment]
Same for me, i'm sorry. Android 8

Was in 0.4.4, tryed without uninstall -> not working
Downloaded 0.6.1b -> not working
Uninstalled 0.4.4, tryed again -> not working

**Comment by XAMIR555** [comment]
@otakuhqz  I do not have any old version but still the application is not installed

**Comment by shawn1thompson** [comment]
@otakuhqz: I uninstalled, deleted cache and data, still failed unfortunately

**Comment by otakuhqz** [comment]
I have replaced the apk in the release section. It is working fine now. [Download here](https://github.com/otakuhqz/ZimLX/releases/download/v0.6.2b/Zim.Launcher.v0.6.2b.build.3010.apk)

**Comment by shawn1thompson** [comment]
Worked for me, but I couldn't update, had to perform a fresh install.

**Comment by otakuhqz** [comment]
I introduced a lot of changes due to compatibility with Android Pie, but going forward you will be able to update

**Comment by josedpedroso** [comment]
Works for me, but getting f-droid users to update could be a problem, as it needs a fresh install.

**Comment by boite** [comment]
0.6.2b Won't install on Android 9.  Never been installed before.  Fails to install "due to an uknown error" :open_mouth:

**Comment by otakuhqz** [comment]
Can you please advise what is your device brand and model?

**Comment by boite** [comment]
Nokia 5.1, Model TA-1061, v3.0.

**Comment by quantizzed** [comment]
I experience the same problem on Xiaomi Mi A1, Android 9.0, app version 0.6.2b.
