### ISSUE TITLE
Version 0.6.2b can't be used horizontally 

### ISSUE THREAD

**Issue by raev33** [otakuhqz/ZimLX#40]
I'm not sure if this is a bug or an planned exclusion, but in version 0.6.2b it seems the launcher can't be used horizontally, making it unfit for use on tablet.
In the old version on f-droid, you could choose, that the launcher could be used both vertically and horisontally, this option seems to be missing now.
Is this on purpose, or is it a bug?

**Comment by otakuhqz** [comment]
I'm working on that feature. Will be included in the next release

**Comment by raev33** [comment]
Great! Thanks for a good launcher!
