### ISSUE TITLE
Plain text restore file

### ISSUE THREAD

**Issue by rjdang** [otakuhqz/ZimLX#41]
What would it take to make the backup/restore files plain text instead of binaries?

My home screen setup is quite complex, and takes me several days of iteration to get right b/c of how painfully slow it is to "hold...drag...drop...hold again...drag again...drop again...etc etc". It would be nice to be able to generate the layout from a json file or something like that.

**Comment by otakuhqz** [comment]
it would be possible but would be required a lot of work since what I save in the file are the wallpaper, SQLite databases, and XML config.
