### ISSUE TITLE
Crash when hitting the home button

### ISSUE THREAD

**Issue by josedpedroso** [otakuhqz/ZimLX#42]
**Describe the bug**
Sometimes, when hitting the Home button to go back to the launcher, it crashes. When this happens, I get stack traces, which I'm attaching. If I press Home again, it usually works.

[traces.txt](https://github.com/otakuhqz/ZimLX/files/3248666/traces.txt)

**To Reproduce**
I haven't found a way to reliably reproduce the issue yet.

**Expected behavior**
The launcher's home screen should show up.

**Smartphone (please complete the following information):**
 - Device: LG G5 H850
 - Stock android 8, rooted

**Comment by otakuhqz** [comment]
Are you using the last version v0.6.2b?

**Comment by josedpedroso** [comment]
Yup.

**Comment by otakuhqz** [comment]
Fixed in commit [b6a12c4](https://github.com/otakuhqz/ZimLX/commit/b6a12c448a9c010c47ad77328eda1dd6845022fa). Will be compiled soon in v0.6.2 build 3012
