### ISSUE TITLE
Feature request: allow moving the drawer icon in the dock

### ISSUE THREAD

**Issue by josedpedroso** [otakuhqz/ZimLX#43]
**Is your feature request related to a problem? Please describe.**
I like having the drawer icon on the right. Also, when using an even number of icons in the dock, the drawer icon will be off-center, which is a bit weird.

**Describe the solution you'd like**
It'd be nice if we could move and remove the drawer icon just by pressing and dragging it. The option to enable/disable the icon (issue #12) could still be used to put it back on or remove it.

**Describe alternatives you've considered**
It's not terribly important, so I guess I can live without this feature, if it's impractical to implement. Swiping up to show the drawer is still an option, after all.

**Comment by otakuhqz** [comment]
It can be enable/disable in the dock settings, I will add the feature to enable drag and drop.

**Comment by otakuhqz** [comment]
implemented in v0.7.1 (creating the drawer icon as widget).
