### ISSUE TITLE
Folder Icon

### ISSUE THREAD

**Issue by Offerel** [otakuhqz/ZimLX#44]
It's it possible to add a feature where we can add icons for folders, so that we can have a folder with shortcuts, but only one icon in the launcher for that folder. The first app in that folder should be the standard icon.

**Comment by otakuhqz** [comment]
I don't think you need a folder to have one shortcut only.
you can change the folder icon, just open the folder, click on the three dots on the bottom right corner, and then tap the icon, that will open the icon chooser view.

**Comment by Offerel** [comment]
I think we may misunderstand each other. I also can't find the three points in the bottom right corner. I'll do the following:

* On the desktop/start screen I have 2 icons.
* I drag icon 2 over icon 1 and then release.
 * A folder is created.
 * It now has 2 shortcuts inside.
 * As icon for the folder itself, I see the two icons as miniatures.
 * But I don't want to see the miniatures, instead i want a single icon.
 * By default the first icon of the two shortcuts in the folder should be used.
 * If possible, if i touch the folder, the first app (the one which builds the folder icon) is started.
 * However, when i swipe that icon as gesture, the folder should be opened.

**Comment by otakuhqz** [comment]
I have tested several times and it works. I will try to make a gif image or a video so you can see the functionality.
but if you have a bug or issue just let me know.

**Comment by Offerel** [comment]
It works now as expected. Many thx for your fantastic work. I had to restart the launcher to show the icon the first time. Several other glitches like labels placeholders and so on are works now also correctly.
