### ISSUE TITLE
Would be nice to see your app at F-Droid

### ISSUE THREAD

**Issue by IzzySoft** [otakuhqz/ZimLX#5]
With your app being Open Source and, if I read your gradle files right, also without proprietary components, it would be nice to have it available at F-Droid – for those who cannot or wantnot use Playstore, and for those who appreciate the extra safety F-Droid gives (checking the source and compiling directly from it, so no "nasty stuff" should sneak in).

Assuming you'd appreciate it being available there, I've opened [a Request For Packaging](https://gitlab.com/fdroid/rfp/issues/642) with F-Droid. The F-Droid tream would much appreciate if you could use tags (see [Creating Releases](https://help.github.com/articles/creating-releases/) in the Github Help), as then new versions could be picked automatically.

**Comment by otakuhqz** [comment]
Hello IzzySoft, for sure I will upload the app to F-Droid in the next days.
I have not done yet since I'm the working alone on this  project and i work few hours of my free time only.

I will check the request for packaging this week.

Thank you for your interest

**Comment by IzzySoft** [comment]
Hi @otakuhqz and thanks for your positive response! No need for you to "upload" anything to F-Droid. Just creating the proper tag(s) will do so F-Droid also can react on updates automatically (whenever you create a new tag; best is having the tag and version name in sync, e.g. using a tag `v1.2.3` for version 1.2.3). F-Droid builds APKs from (your) source, they don't take binaries.

**Comment by otakuhqz** [comment]
Hi @IzzySoft, can you please advise how can I (or you) run the f-droid bot to scan the app?
I have checked and it doesn't appear in the F-Droid platform yet.

Thanks

**Comment by IzzySoft** [comment]
Thanks for the heads-up! The bot has already been run. Now it needs a dev to make the build recipe. The issue is still open, and F-Droid is permanently "under-staffed". I've just pinged 3 of our devs, so one of them hopefully picks up soon.

**Comment by offa** [comment]
Just landed: https://f-droid.org/de/packages/org.zimmob.zimlx/

**Comment by IzzySoft** [comment]
Thanks to all who helped! @otakuhqz I close this issue then as it is solved.
