### ISSUE TITLE
Bugs with folders

### ISSUE THREAD

**Issue by Pablo-Balaudo** [otakuhqz/ZimLX#50]
When I create a folder and start adding icons to it until it gets big enough to be 4x4, if I then add another icon the Launcher crashes (not always as it happens at random).

Another bug that may be related and also happens at random is this one where I try to move an app inside a folder, but immediately disappear from the folder after I tried to grab app to move it. The folder readjust it's size because it lost an icon, but if restart the Launcher the app is in the folder again with it's original size.

Then there is this visual bug that it's not really that important, but if I am dragging an app or folder to move it on the desktop, all the folders (except the one I am dragging) that have their contents as an icon (a part of all the apps inside the folder) have their apps trespassing the limits of the round icon of the folder.

Last but not least, I don't know if this is a bug, but in the "App Drawer" settings if I change the number of columns, the App Drawer doesn't change at all (even if I restart the Launcher). But if I go to the "Desktop" settings and change the Width on the Grid Size the number of columns on the Desktop changes (as expected), but the number of columns in the App Drawer also changes to the one specified on the grid. So either the Grid Size overrides the settings in the App Drawer about the number of columns or I just don't understand what "the number of columns" setting is referring to.

Build version: 0.6.2b
Device: Motorola Moto G (4)
OS: Android 7

**Comment by otakuhqz** [comment]
thank you for your feedback
1. Folder issue: fixed
2. the apps trespassing the limits fixed as well
3. this was an issue since I was taking the same value for desktop and apply to the drawer. that was fixed a few days ago.
