### ISSUE TITLE
Quality life changes

### ISSUE THREAD

**Issue by Pablo-Balaudo** [otakuhqz/ZimLX#51]
It would be nice if by pressing the Arrow in the Dock, the App Drawer would open (just as if it was the Dock Button), instead of having to swipe it up.

Another thing is that the "Minibar" settings and the "About" page don't respect the colors of the theme.

Lastly there is this Icon Pack in Theme settings that's called "%s" I don't know if it's a bug in the display of the name or not. Also in Home Widget there is this setting called "Display %1$s" that when I turn it on nothing happens on the Desktop, and when I return to settings, it turned itself off.

**Comment by otakuhqz** [comment]
A lot of changes were introduced in v0.6.1 and some options are not upgraded yet. I released the las version to fix a lot of bugs and crashes in v0.4.4 and to add support for Android Pie. Hopefully in v0.6.2 all the above issues will be fixed.
