### ISSUE TITLE
Wallpaper selection dialog not working

### ISSUE THREAD

**Issue by jxosborne** [otakuhqz/ZimLX#59]
**Describe the bug**
Cannot change desktop wallpaper using the inbuilt wallpaper selector.

**To Reproduce**
-From the desktop: Long press to get the selection menu (Home settings, Widgets, Wallpapers)
-Select "Wallpapers".
-Toast notification pops up saying "Application isn't installed".

**Expected behavior**
Wallpaper gallery should be presented.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Sony XZ1 Compact
 - OS: LOS 16.0
 - Browser: N/A
 - Version N/A

**Additional context**
If I use the wallpaper selector from the minibar, it works as expected.  I've also tried installing Lawnchair to see if the problem persists, and it is also working as expected.

**Comment by otakuhqz** [comment]
fixed in the recent commit

**Comment by Seferi** [comment]
I'm having the same problem on LOS 16
