### ISSUE TITLE
Possibly get 12 hour time?

### ISSUE THREAD

**Issue by michaelgray2020** [otakuhqz/ZimLX#68]
Is there any way to switch time on home screen to 12 hour instead of military or 24 hour time?

**Comment by otakuhqz** [comment]
Yes, It is the home widget screen.

**Comment by otakuhqz** [comment]
![Screenshot_1569876637](https://user-images.githubusercontent.com/6044050/65921504-a50e6500-e39f-11e9-8724-be88acd4d654.png)

**Comment by otakuhqz** [comment]
[tab.](url)
