### ISSUE TITLE
Add a way to build the app without Play Services

### ISSUE THREAD

**Issue by Rudloff** [otakuhqz/ZimLX#7]
**Is your feature request related to a problem? Please describe.**
I am working on packaging ZimLX on F-Droid (https://github.com/otakuhqz/ZimLX/issues/5).
`play-services-awareness` is a non-free library and we don't allow those so we had to remove it and the AwarenessWeatherAPI class. We also patched the preferences to enable OpenWeatherMap by default.
You can see the exact changes we made here: https://gitlab.com/fdroid/fdroiddata/blob/8a955a2a0f10e6824f3fe62310e4e869d8e3ea31/metadata/org.zimmob.zimlx.txt#L20

**Describe the solution you'd like**
It would be a lot easier for us to maintain the F-Droid package if this could be handled with a [build variant](https://developer.android.com/studio/build/build-variants) that removes this dependency automatically.
Do you think that is something you could do?

**Describe alternatives you've considered**
Since this class comes from Lawnchair, I guess the solution could be shared with them.

**Additional context**
F-Droid can only include an app if it is entirely open-source and its dependencies are open-source as well.
We frequently remove non-free dependencies from apps but ou patches can break easily if the upstream files change, so it is way easier for us if this is handled by the upstream developer.

**Comment by otakuhqz** [comment]
Hello @Rudloff 
I have decided to remove the weather api since this is not a feature I want to offer in the launcher.
the commit [remove weather support](https://github.com/otakuhqz/ZimLX/commit/98a45d6f6a612abcbb7273ba906886d3decd7ab6) fix this issue.

Thanks

**Comment by Rudloff** [comment]
OK, then it will be even easier for us to package the app.
Can you please ping me when you publish a new stable release that includes this change?
