### ISSUE TITLE
Master branch doesn't compile

### ISSUE THREAD

**Issue by damoasda** [otakuhqz/ZimLX#78]
**Describe the bug**
The master branch doesn't compile. I get a compilation error in the class SuperGContainerView:
`mQsbColor = prefs.getGoogleColor();`
error: cannot find symbol method getGoogleColor()

**To Reproduce**
1. Create new Android Studio project from version control: https://github.com/otakuhqz/ZimLX.git
2. Click on the "Run app" button.

**Expected behavior**
The source code compiles without errors.

**Additional context**
The bug seems to be created by commit f6eefae8421ebd29f6caf5a1a5dde0f0fc3e58ca.

**Comment by otakuhqz** [comment]
I forgot to include the ZimPreferences in the commit.

**Comment by otakuhqz** [comment]
I have updated the ZimPreferences class in commit https://github.com/otakuhqz/ZimLX/commit/94f440b3916049b2462a76b0804c9dfcc5ea5665

**Comment by damoasda** [comment]
Thank you for the fast fix, now I can compile and run the head version.
